### ISSUE TITLE
XSS issue.

### ISSUE THREAD

**Issue by AshamedConsequence** [DGKSK8LIFE/AwtySM#38]
Where: Session.html
Problem: Chat element does not espace dangerous characters.
How to fix: https://www.werockyourweb.com/url-escape-characters/

**Comment by DGKSK8LIFE** [comment]
not an XSS issue because it only affects the client side (apart from sending HTML tags I think);
Correction: Chat does not escape characters, but reduces its risk by deleting illegal characters before they can realistically be submitted, though some users are fast fingered enough to submit them when copy-pasting
I've already escaped symbols like quotes for database writes (to avoid errors), so this is easy to solve. Eventually, I want a the rewrite elements of the chat system so that there are no "forbidden characters"'; free input

**Comment by DGKSK8LIFE** [comment]
also the link you sent isn't a solution for the HTML input event; it's for escaping characters from files/URLs

**Comment by DGKSK8LIFE** [comment]
working on a solution with this: https://stackoverflow.com/questions/6234773/can-i-escape-html-special-chars-in-javascript

**Comment by DGKSK8LIFE** [comment]
fixed and supports all input
